# Generated by Django 4.2.15 on 2024-09-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('services_offered', models.TextField()),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ratings', models.FloatField(default=0.0)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='RetiredExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_services', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('previous_positions', models.TextField(blank=True, null=True)),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='experts.expert')),
            ],
        ),
    ]
